In [39]:
import numpy as np

In [40]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# 넘파이를 사용하는 이유는요 안의 기본 코어가 C 기반으로 되어 있기 때문에 굉장히 속도가 빠름
# 나중에 시간측정을 해보면 10배 정도는 기본적으로 빠르다

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a.dtype

dtype('int32')

In [42]:
type(a)

numpy.ndarray

In [43]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [44]:
a = a.astype(np.float32) # a = astype('float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [45]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.arange(1, 13).reshape(3, 2, 2)
# 3차원 이상의 어레이를 볼때는 괄호의 개수로 이해하는 게 편하다

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [48]:
# 결측치를 넣어보자
np.nan * 10

nan

In [49]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [50]:
a[0][1] = np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [51]:
# int에서는 nan을 사용할 수 없다. float에서 사용해야 함
a = np.linspace(1, 10, 20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [52]:
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [54]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [55]:
# 행렬의 곱
data.dot(data, data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [56]:
data@data
# 왜 행렬의 곱 안함?

array([[ 7560,  9288, 11016],
       [17118, 21033, 24948],
       [26676, 32778, 38880]])

In [57]:
# 0차원 : 스칼라
a = np.array(1)
a
a.shape
a.ndim

0

In [58]:
# 1차원 : 벡터
a = np.array([1])
print(a)
print(a.shape)
print(a.ndim)

[1]
(1,)
1


In [59]:
# 2차원 : 행렬(메트릭스)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [60]:
# 3차원 : 3차원 이상의 다차원의 행렬을 Tensor라고 부른다
a = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(a)
print(a.shape)
print(a.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [61]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [62]:
b = np.ones(12).reshape(2, 3, 2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [63]:
c = np.zeros(12).reshape(2, 3, 2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [64]:
# 단위행렬 = 자신과 곱했을 때 자신이 나옴/자신과 자신의 역행렬을 곱했을 때 역행렬이 나옴
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
e = np.zeros([3, 4, 2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [66]:
# empty는 0에 가까운 값이 있는 값으로 채움
f = np.empty([2, 3])
f

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313]])

In [67]:
g = np.full([3, 4], 1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [68]:
# 집계 함수
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
np.mean(a) # 평균

4.5

In [70]:
np.median(a) # 중앙값

4.5

In [71]:
np.std(a) # 표준편차

2.8722813232690143

In [72]:
np.sum(a)

45

In [73]:
np.sum(a, axis=0)

array([ 5,  7,  9, 11, 13])

# pandas

In [74]:
import numpy as np
import pandas as pd

In [75]:
data = np.arange(0, 50, 10)
data

array([ 0, 10, 20, 30, 40])

In [76]:
a = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [77]:
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [78]:
a['b']

10

In [79]:
a.loc['b']

10

In [80]:
a.iloc[1]

10

In [81]:
# 산술연산
a + 10

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [82]:
rawData = np.random.randint(50, 100,  size=(4, 3))
rawData

array([[69, 98, 98],
       [65, 84, 62],
       [57, 59, 82],
       [69, 61, 61]])

In [83]:
df = pd.DataFrame(rawData, 
                  index=['1반', '2반', '1반', '2반'], 
                  columns=['국', '영', '수'])
df

국   영   수
1반  69  98  98
2반  65  84  62
1반  57  59  82
2반  69  61  61

In [84]:
df['국']

1반    69
2반    65
1반    57
2반    69
Name: 국, dtype: int32

In [85]:
df[0]

KeyError: 0

In [86]:
df['평균'] = round((df['국'] + df['영'] + df['수'])/3, 2)
df

국   영   수     평균
1반  69  98  98  88.33
2반  65  84  62  70.33
1반  57  59  82  66.00
2반  69  61  61  63.67

In [87]:
df['nan'] = np.nan
df

국   영   수     평균  nan
1반  69  98  98  88.33  NaN
2반  65  84  62  70.33  NaN
1반  57  59  82  66.00  NaN
2반  69  61  61  63.67  NaN

In [88]:
del df['nan']
df

국   영   수     평균
1반  69  98  98  88.33
2반  65  84  62  70.33
1반  57  59  82  66.00
2반  69  61  61  63.67

In [89]:
df[df.평균 > 75]

국   영   수     평균
1반  69  98  98  88.33

In [90]:
df = df.drop(['평균'], axis='columns')
df

국   영   수
1반  69  98  98
2반  65  84  62
1반  57  59  82
2반  69  61  61

In [92]:
df = df.astype('float64')
df

국     영     수
1반  69.0  98.0  98.0
2반  65.0  84.0  62.0
1반  57.0  59.0  82.0
2반  69.0  61.0  61.0

In [94]:
df['수'][2] = np.nan
df

국     영     수
1반  69.0  98.0  98.0
2반  65.0  84.0  62.0
1반  57.0  59.0   NaN
2반  69.0  61.0  61.0

In [96]:
df.dropna(axis=0)

국     영     수
1반  69.0  98.0  98.0
2반  65.0  84.0  62.0
2반  69.0  61.0  61.0

In [97]:
df

국     영     수
1반  69.0  98.0  98.0
2반  65.0  84.0  62.0
1반  57.0  59.0   NaN
2반  69.0  61.0  61.0

In [98]:
df.dropna(axis=0, inplace=True)
df

국     영     수
1반  69.0  98.0  98.0
2반  65.0  84.0  62.0
2반  69.0  61.0  61.0

In [99]:
df

국     영     수
1반  69.0  98.0  98.0
2반  65.0  84.0  62.0
2반  69.0  61.0  61.0

In [100]:
df.T

1반    2반    2반
국  69.0  65.0  69.0
영  98.0  84.0  61.0
수  98.0  62.0  61.0